import 'package:satellite_hex_parsing/models/device_type.dart';

class MessageStructure {
  static final Map<DeviceType, Map<String, Map<String, List<int>>>>
  _structures = {
    DeviceType.udoseAg: {
      'ARM_MESSAGE': {
        'session_id': [4, 10],
        'minimum_flowrate': [14, 11],
        'prefert_minutes': [25, 14],
        'prefert_units': [39, 1],
        'prefert_volume': [40, 17],
        'fertigation_duration_minutes': [57, 14],
        'fertigation_volume_litres': [71, 16],
        'warning_code': [87, 8],
      },
      'FLOW_MESSAGE': {
        'session_id': [4, 10],
        'run_data_id': [14, 5],
        'first_5_mins_water': [19, 13],
        'first_5_mins_fert': [32, 13],
        'second_5_mins_water': [45, 13],
        'second_5_mins_fert': [58, 13],
        'third_5_mins_water': [71, 13],
        'third_5_mins_fert': [84, 13],
        'fourth_5_mins_water': [97, 13],
        'fourth_5_mins_fert': [110, 13],
        'max_pressure_in_20bins': [123, 8],
      },
      'STARTED_MESSAGE': {
        'session_id': [4, 10],
        'latitude': [14, 24],
        'longitude': [38, 25],
        'current_tank_pressure': [63, 10],
        'current_battery_voltage': [73, 8],
        'fertigation_run': [81, 1],
      },
      'DAILY_MESSAGE': {
        'latitude': [4, 24],
        'longitude': [28, 25],
        'lowest_battery_voltage': [53, 8],
        'highest_battery_voltage': [61, 8],
        'highest_solar_voltage': [69, 8],
        'uptime_today': [77, 7],
        'telemetry_major_version': [84, 4],
        'telemetry_minor_version': [88, 4],
        'board_firmware_major_version': [92, 4],
        'board_firmware_minor_version': [96, 4],
      },
      'END_OF_RUN_MESSAGE': {
        'session_id': [4, 10],
        'prefertigation_litres_water': [14, 18],
        'fertigation_litres_water': [32, 20],
        'post_fertigation_litres_water': [52, 18],
        'fertigation_litres_fertiliser': [70, 16],
        'stop_reason': [86, 5],
        'final_tank_pressure': [91, 10],
        'final_battery_voltage': [101, 8],
        'total_run_battery_amp_hours': [109, 8],
      },
    },
    DeviceType.udose: {
      'ALARM_MESSAGE': {
        'error_code': [4, 8],
        'error_data': [12, 18],
        'water_flow': [30, 21],
        'nutrient_flow': [51, 21],
        'is_running': [72, 1],
        'is_alarm': [73, 1],
        'battery_voltage': [74, 8],
        'solar_voltage': [80, 8],
      },
      'BI_HOURLY_MESSAGE': {
        'water_flow': [4, 21],
        'nutrient_flow': [25, 21],
        'is_running': [46, 1],
        'is_alarm': [47, 1],
        'battery_voltage': [48, 8],
        'solar_voltage': [56, 8],
        'prev_water_flow': [64, 21],
        'prev_nutrient_flow': [85, 21],
        'prev_is_running': [106, 1],
        'prev_is_alarm': [107, 1],
        'prev_battery_voltage': [108, 8],
        'prev_solar_voltage': [116, 8],
      },
      'FOUR_HOURLY_MESSAGE': {
        'trigger_point': [4, 10],
        'target_dose': [14, 15],
        'highest_conductivity': [29, 9],
        'lowest_conductivity': [38, 9],
        'water_temperature': [47, 8],
        'nutrient_temperature': [55, 8],
        'nutrient_tank_level': [63, 16],
        'error_code': [87, 8],
        'doses_skipped_in_four_hours': [95, 8],
        'leakage_in_four_hours': [103, 12],
        'flow_meter_warning': [115, 1],
        'conductivity_comms_warning': [116, 1],
        'poor_doses': [117, 2],
        'missed_doses': [119, 2],
        'has_water_flow': [121, 1],
        'has_dosed': [122, 1],
        'has_rain_ticks': [123, 1],
      },
      'DAILY_MESSAGE': {
        'water_flow': [4, 31],
        'nutrient_flow': [35, 31],
        'rainfall': [66, 10],
        'pump_runtime': [76, 16],
        'dose_count': [92, 16],
      },
      'CURRENT_HOUR_MESSAGE': {
        'water_flow': [12, 21],
        'nutrient_flow': [33, 21],
        'is_running': [54, 1],
        'is_alarm': [55, 1],
        'battery_voltage': [56, 8],
        'solar_voltage': [64, 8],
      },
      'SETTINGS_MESSAGE': {
        'water_meter_ppl_or_lpp': [4, 3],
        'nutrient_meter_ppl': [7, 2],
        'dosing_mode': [9, 2],
        'nutrient_probe_mode': [11, 2],
        'conductivity_probe_mode': [13, 2],
        'telemetry_mode': [15, 2],
        'trigger_point': [17, 9],
        'target_dose': [26, 12],
        'dose_runtime': [38, 14],
        'max_pump_runtime': [52, 15],
        'ml_while_pump_off_alarm': [67, 8],
        'nutrient_tank_capacity': [75, 14],
        'nutrient_tank_height': [89, 14],
        'nutrient_tank_current_level': [103, 14],
        'conductivity_skip_level': [117, 10],
        'conductivity_alarm_level': [127, 10],
        'conductivity_skip_limit': [137, 5],
        'supplement_id': [142, 3],
        'nutrient_concentration': [145, 7],
        'livestock_count': [152, 15],
        'telemetry_major_version': [167, 5],
        'board_firmware_year': [172, 4],
        'board_firmware_month': [176, 4],
        'board_firmware_day': [180, 5],
        'water_flow_unit': [185, 1],
        'water_flow_limit_per_hr': [186, 10],
        'recent_startup': [196, 1],
        'new_nutrient_selection': [201, 7],
      },
    },
    DeviceType.ubot: {
      'DAILY_MESSAGE': {
        'major_version': [0, 4],
        'minor_version': [4, 4],
        'patch_version': [8, 4],
        'battery_voltage_high': [12, 5],
        'battery_voltage_low': [17, 5],
        'pressure_reading_1': [22, 13],
        'pressure_reading_2': [35, 13],
        'pressure_reading_3': [48, 13],
        'pressure_reading_4': [61, 13],
        'pressure_reading_5': [74, 13],
        'pressure_reading_6': [87, 13],
        'day': [100, 5],
        'last_reading_hour': [105, 5],
        'rainfall': [110, 10],
      },
    },
  };

  static Map<String, List<int>>? getStructure(
    DeviceType deviceType,
    String messageType,
  ) {
    return _structures[deviceType]?[messageType];
  }

  static List<String> getMessageTypes(DeviceType deviceType) {
    return _structures[deviceType]?.keys.toList() ?? [];
  }
}
